### ISSUE TITLE
Required Children Props

### ISSUE THREAD

**Issue by chrisbeedie** [jplayer/react-jPlayer#12]
Would it be possible to relax the need for children props on some of the controls (e.g. play, previous, next)? I'm recreating something similar to the SoundManager2 Bar-UI theme, and essentially making the play button transparent over my control, so don't need to add a child.

**Comment by MartinDawson** [comment]
@chrisbeedie Good idea. They shouldn't be required anyway because you can set an icon with css too and not need children. I'll remove them.

**Comment by MartinDawson** [comment]
Thanks for the comment @chrisbeedie. Actually going to leave them for now. I don't really want to change them when 99% of users require them. You can add dummy children for now to suppress the warnings such as an empty div.

I created an issue: https://github.com/facebook/prop-types/issues/135

**Comment by MartinDawson** [comment]
@chrisbeedie Can you provide an example or jsfiddle as to why you don't need the child? I'm still unsure what you are trying to do exactly. Thanks.

**Comment by chrisbeedie** [comment]
@MartinDawson Yup, very easily worked around, I was more just wondering why it was required.

I've created a minimal example here: https://jsfiddle.net/fyb40z87/ I've used the emitted html to remove external dependencies

I'm taking inspiration from http://www.schillmania.com/projects/soundmanager2/demo/bar-ui/
