### ISSUE TITLE
Play/Pause state on new media selection

### ISSUE THREAD

**Issue by clim-amplify** [jplayer/react-jPlayer#2]
When using `react-jplayer` to select new media the initial state of the media seems to be paused, however a double click on the media is needed to play. This only occurs when the `currentMedia` is **playing**. When `currentMedia` is **paused**, selecting new media will cause the new media to autoplay. 

I think there may be an issue with the way the initial state is set when loading new media. Not sure if this is intended behavior, but just wanted to raise the issue.

We added the following code to `mediaContainer.js` in `componentWillReceiveProps`. There may be a better solution as this was a quick fix.

```
if (
    // same media
    ((this.props.mediaId === nextProps.mediaId) &&
    (!this.props.paused && nextProps.paused)) ||
     // media changed
    ((this.props.mediaId !== nextProps.mediaId) && nextProps.paused)
) {
    this.currentMedia.pause();		        
} else if (
    // same media
    ((this.props.mediaId === nextProps.mediaId) &&
    (this.props.paused && !nextProps.paused)) ||
    // media changed
    ((this.props.mediaId !== nextProps.mediaId) && !nextProps.paused)
) {
    this.currentMedia.play();
}
```

**Comment by MartinDawson** [comment]
@clim-amplify Thanks for bringing this to my attention. I'll look into it soon. A V6 of react-jPlayer will fix these currentMedia pause/playing issues and is in the works.

**Comment by MartinDawson** [comment]
@clim-amplify Can you try and replicate this in react-jPlayer v6? Hopefully it's fixed now.
