### ISSUE TITLE
 mediaContainer.js:335 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

### ISSUE THREAD

**Issue by pengteling** [jplayer/react-jPlayer#4]
when mp3 play ended , console error

mediaContainer.js:335 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

**Comment by MartinDawson** [comment]
@pengteling v6 react-jPlayer will fix this and will be released sometime late next week hopefully. Thanks.

**Comment by MartinDawson** [comment]
@pengteling It's fixed in V6 now if you get the latest. It's not really an error though and can be safely ignored if you see it again.
