### ISSUE TITLE
play .rm real media player files

### ISSUE THREAD

**Issue by prog20901** [jplayer/react-jPlayer#6]
Hi,

We have lots of .rm real media player files and would like to play it on the web.

not sure how to make it work for .rm files

thanks.

**Comment by MartinDawson** [comment]
@jkathir Never heard of that extension before. I'll look into supporting it tonight.

**Comment by MartinDawson** [comment]
@jkathir .rm is not a supported audio or video format for html5 player. React-jplayer just wraps the html5 player which means we can not support this file format. https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#File_Formats
