### ISSUE TITLE
Must use Redux?

### ISSUE THREAD

**Issue by willwen** [jplayer/react-jPlayer#8]
Hi all,
I know the project says there is a dependency on Redux, but I am new to Redux and not sure what that means. 
My current project uses only React, so states and props, but no stores and providers. I see in app.jsx, we "wrap the player in the redux provider"
```
  <Provider store={store}>
    <AudioPlayer />
  </Provider>
```
My question is can I just avoid using Providers and Stores since I don't know redux and still acheive the same functionality by passing state and properties?

**Comment by MartinDawson** [comment]
It means that this library must use Redux somewhere for it to be able to work. This doesn't have to be your root component but you will need to use it somewhere. Whichever component you wrap in `<Provider />`, the components beneath it will have access to your jPlayers in the state so you can modify the options, play/pause media and stuff, any component that is not beneath this `<Provider />` will not be able to make any modifications to your jPlayers though.

You should probably read up on the basics of Redux before using this library to understand state management.

**Comment by willwen** [comment]
okay thank you for the swift reply, I'll slowly get into redux. I'll close this issue
